"""Mã lõi (BE-00 §4), mọi prompt dùng chung. Mã riêng khai ở module sở hữu."""

from packages.core.errors import ERRORS

# Chung
VALIDATION = ERRORS.define("VALIDATION", 422)
PATH_BODY_MISMATCH = ERRORS.define("PATH_BODY_MISMATCH", 422)
MALFORMED_JSON = ERRORS.define("MALFORMED_JSON", 400)
CURSOR_INVALID = ERRORS.define("CURSOR_INVALID", 422)
NOT_FOUND = ERRORS.define("NOT_FOUND", 404)
FORBIDDEN = ERRORS.define("FORBIDDEN", 403)
PAYLOAD_TOO_LARGE = ERRORS.define("PAYLOAD_TOO_LARGE", 413)
RATE_LIMITED = ERRORS.define("RATE_LIMITED", 429)
DEPENDENCY_UNAVAILABLE = ERRORS.define("DEPENDENCY_UNAVAILABLE", 503)
INTERNAL = ERRORS.define("INTERNAL", 500)

# Phiên
UNAUTHENTICATED = ERRORS.define("UNAUTHENTICATED", 401)
INVALID_CREDENTIALS = ERRORS.define("INVALID_CREDENTIALS", 401)
SESSION_REVOKED = ERRORS.define("SESSION_REVOKED", 401)
ACCOUNT_DISABLED = ERRORS.define("ACCOUNT_DISABLED", 403)
ORIGIN_MISMATCH = ERRORS.define("ORIGIN_MISMATCH", 403)

# Version / idempotency
VERSION_CONFLICT = ERRORS.define("VERSION_CONFLICT", 409)
PRECONDITION_REQUIRED = ERRORS.define("PRECONDITION_REQUIRED", 428)
IDEMPOTENCY_KEY_REUSED = ERRORS.define("IDEMPOTENCY_KEY_REUSED", 422)
IDEMPOTENCY_IN_PROGRESS = ERRORS.define("IDEMPOTENCY_IN_PROGRESS", 503)  # kèm Retry-After: 1

# Tệp (U-case)
IMAGE_TOO_LARGE = ERRORS.define("IMAGE_TOO_LARGE", 422)
PDF_UNREADABLE = ERRORS.define("PDF_UNREADABLE", 422)
FILE_CORRUPT = ERRORS.define("FILE_CORRUPT", 422)
FILE_TYPE_MISMATCH = ERRORS.define("FILE_TYPE_MISMATCH", 422)
UPLOAD_INCOMPLETE = ERRORS.define("UPLOAD_INCOMPLETE", 422)
UPLOAD_SIZE_MISMATCH = ERRORS.define("UPLOAD_SIZE_MISMATCH", 422)
CAD_NOT_SUPPORTED = ERRORS.define("CAD_NOT_SUPPORTED", 422)
