"""Lượt dọn `db_url` (FIX-112) trên bảng có dữ liệu gốc và cột `Identity()` (NO-277).

Dữ liệu gốc do migration nạp phải sống qua lượt dọn, **và** bộ đếm `Identity()` của bảng đó phải
đứng sau dòng gốc: đặt về 1 trước khi nạp lại là dòng thêm đầu tiên của test sau đụng khoá chính.
"""

import asyncio
from dataclasses import replace

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

from packages.db.engine import GATE_CONNECT_TIMEOUT_S
from packages.testing.fixtures import db as db_fixtures

TABLE = "reset_plan_seeded_identity"
"""Tên bảng thử; câu SQL ghi thẳng tên (không f-string) để không phải miễn S608."""


async def _run(url: str, statements: list[str]) -> list[object]:
    """Chạy từng câu (AUTOCOMMIT) trên `url`, trả kết quả vô hướng của câu cuối nếu có."""
    engine = create_async_engine(url, isolation_level="AUTOCOMMIT", connect_args={"timeout": GATE_CONNECT_TIMEOUT_S})
    try:
        async with engine.connect() as connection:
            result = None
            for statement in statements:
                result = await connection.execute(text(statement))
            return list(result.scalars()) if result is not None and result.returns_rows else []
    finally:
        await engine.dispose()


def test_reset_plan__identity_counter_follows_reloaded_seed(db_url: str, shared_db: db_fixtures.SharedDb) -> None:
    """Sau lượt dọn, dòng gốc còn nguyên và dòng mới nhận id kế sau dòng gốc, không đụng khoá chính."""
    asyncio.run(
        _run(
            db_url,
            [
                "CREATE TABLE reset_plan_seeded_identity"
                " (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text)",
                "INSERT INTO reset_plan_seeded_identity (name) VALUES ('seed-1'), ('seed-2')",
            ],
        )
    )
    try:
        plan = asyncio.run(db_fixtures._build_reset_plan(db_url))
        asyncio.run(_run(db_url, ["INSERT INTO reset_plan_seeded_identity (name) VALUES ('test-row')"]))

        replace(shared_db, plan=plan).reset()

        ids = asyncio.run(_run(db_url, ["INSERT INTO reset_plan_seeded_identity (name) VALUES ('next') RETURNING id"]))
        names = asyncio.run(_run(db_url, ["SELECT name FROM reset_plan_seeded_identity ORDER BY id"]))
        assert ids == [3]
        assert names == ["seed-1", "seed-2", "next"]
    finally:
        asyncio.run(
            _run(
                db_url,
                [
                    f"DROP TABLE IF EXISTS {TABLE}",
                    f'DROP TABLE IF EXISTS "{db_fixtures.RESET_SCHEMA}"."{TABLE}"',
                ],
            )
        )


def test_shared_db_reset__reuses_one_connection(
    shared_db: db_fixtures.SharedDb, monkeypatch: pytest.MonkeyPatch
) -> None:
    """NO-267: các lượt dọn liền nhau đi trên **một** kết nối Postgres, không mở kết nối mới mỗi test.

    Đọc `pg_backend_pid()` qua chính engine mà `SharedDb.reset` đưa cho `_reset`, ngay sau mỗi lượt:
    lượt dọn nào dựng engine (hay kết nối) mới thì pid đổi. Nghe sự kiện `connect` trên
    `shared_db.engine` thì không bắt được hồi quy đó — engine mới không phải engine đang nghe.
    """
    pids: list[int] = []
    real_reset = db_fixtures._reset

    async def reset_then_read_pid(engine: AsyncEngine, url: str, statements: list[str]) -> None:
        """Chạy lượt dọn thật rồi ghi pid của kết nối mà pool của lượt dọn trả lại."""
        await real_reset(engine, url, statements)
        async with engine.connect() as connection:
            pids.append((await connection.execute(text("SELECT pg_backend_pid()"))).scalar_one())

    monkeypatch.setattr(db_fixtures, "_reset", reset_then_read_pid)
    for _ in range(3):
        shared_db.reset()
    assert len(pids) == 3
    assert len(set(pids)) == 1
